PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX wine: <http://swat.cse.lehigh.edu/onto/wine.owl#>

SELECT ?X
WHERE {
  ?X rdf:type wine:Wine .
  ?X wine:locatedIn wine:CaliforniaRegion .
}
